### PR TITLE
Drop empty lines

### PR DESCRIPTION
**Pull request by xaizek**
I've noticed presence of trailing empty lines in all three windows, which isn't a big deal, but is annoying enough to want to get rid of them.

### CODE REVIEW

**Comment by rhysd** [comment]
@xaizek 

Thank you for catching this. I confirmed that this is a bug and I can fix it by using `setline()` instead of `append()`. So I fixed it at 6d110a5. It would be better than removing empty lines later. Could you please update this plugin to the latest and confirm that this issue was fixed?

**Comment by xaizek** [comment]
Yes, `setline()` is a better way, but your commit addresses only diff and status windows (239d976) and not the edit window (41e0a98), which still has trailing empty line on `master`.

**Comment by rhysd** [comment]
Oh, thank you for pointing it. I'll look into it.

**Comment by rhysd** [comment]
I cherry-picked your commit 41e0a98 into master. Thanks.

**Pull request closed without merging**
